title: "Introduction to Bioimage Analysis"
author       : "Pete Bankhead"  # The author of the book
copyright    : "2022"  # Copyright year to be placed in the footer
logo         : 'images/book-logo-smaller.png'

exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", '_unused/**', 'nbs/*']
# only_build_toc_files: true

execute:
  execute_notebooks: "auto"

repository:
  url           : https://github.com/petebankhead/jupyter-book/ # Online location of your book
  branch        : main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  thebe         : true
  notebook_interface : "classic"
  binderhub_url      : "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)

parse:
  myst_enable_extensions:
    - colon_fence
    - linkify
    - dollarmath
    - substitution
    - html_image

sphinx:
  config:
    bibtex_bibfiles:
      - "references.bib"
    html_js_files:
      # Only needed if plotly is used
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

latex:
  latex_engine: xelatex
