name: bioimage-book
channels:
  - conda-forge
dependencies:
  - python=3.10
  - aicsimageio=4.10.*
  - imageio
  - jupyter-book=0.15.*
  - jupytext
  - matplotlib=3.8.*
  - myst-nb
  - nbclassic=1.0.*
  - sphinx-sitemap=2.5.*
  - numpy=1.26.*
  - pandas=2.2.*
  - scikit-image=0.22.*
  - scipy=1.12.*
  - sphinx-intl=2.1.*
  - sphinx-sitemap=2.5.*