name: bioimage-book
channels:
  - conda-forge
dependencies:
  - python=3.10
  - aicsimageio=4.10.*
  - imageio
  - jupyter-book=0.15.*
  - jupytext
  - matplotlib=3.7.*
  - myst-nb
  - nbclassic=1.0.*
  - numpy=1.24.*
  - pandas=2.0.*
  - scikit-image=0.20.*
  - scipy=1.10.*
  - sphinx-intl=2.1.*
  - sphinx-sitemap=2.5.*
